name: Test Results

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  publish-test-results:
    name: Publish Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    steps:
      - name: Download and Extract Artifacts
        uses: EnricoMi/action-download-artifact@master
        with:
          run_id: ${{ github.event.workflow_run.id }}
          filter: " Test Results "
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          junit_files: "artifacts/* Test Results*/**/*.xml"
